site_name: University of Everything
site_description: An integrated curriculum for systems thinkers, engineers, strategists, and humanists.
repo_url: https://github.com/REPLACE-USER/university-of-everything
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: teal
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - About:
    - Vision: about/vision.md
  - Handbook:
    - Program Structure: handbook/structure.md
    - Workload Philosophy: handbook/workload-philosophy.md
    - Assessment Standards: handbook/assessment-standards.md
    - Portfolio Guide: handbook/portfolio-guide.md
  - Catalog:
    - Overview: catalog/overview.md
    - By Year:
      - Year 1: catalog/by-year/year-1.md
    - By Pillar:
      - Math & Logic: catalog/by-pillar/math-logic.md
      - Science & Engineering: catalog/by-pillar/science-engineering.md
      - Business & Economics: catalog/by-pillar/business-econ.md
      - Humanities & Civic: catalog/by-pillar/humanities-civic.md
      - Life / Creativity / Meta: catalog/by-pillar/life-creativity-meta.md
      - Capstones: catalog/by-pillar/capstones.md
