site_name: University of Everything
site_description: An integrated curriculum for systems thinkers, engineers, strategists, and humanists.
repo_url: https://github.com/m4xbrg/university-of-everything

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: teal

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - overrides/extra.css

plugins:
  - search:
      prebuild_index: true
  - sitemap:
      changefreq: weekly
      priority: 0.5

nav:
  - Home: index.md
  - Pillars:
    - Math & Logic: indexes/math-logic.md
    - Science & Engineering: indexes/science-engineering.md
    - Business & Economics: indexes/business-econ.md
    - Humanities & Civic: indexes/humanities-civic.md
    - Life / Creativity / Meta: indexes/life-creativity-meta.md
    - Capstones: indexes/capstones.md
  - Assignments:
    - Overview: assignments/README.md
    - Sequences:
      - Calculus I (10 weeks): assignments/sequences/calculus-1/README.md
      - Physics I: Mechanics (10 weeks): assignments/sequences/physics-1-mechanics/README.md
      - Strategy I (10 weeks): assignments/sequences/strategy-1-competitive-advantage/README.md
      - Control Systems (10 weeks): assignments/sequences/ece-3-control-systems/README.md
      - Linear Algebra I (10 weeks): assignments/sequences/linear-algebra-1/README.md
      - Multivariable Calculus (10 weeks): assignments/sequences/multivariable-calculus/README.md
      - Energy Systems I (10 weeks): assignments/sequences/energy-systems-1/README.md
    - Banks:
      - Math — Calculus: assignments/banks/math-calculus/
      - Linear Algebra: assignments/banks/linear-algebra/
      - Probability: assignments/banks/probability/
      - Differential Equations: assignments/banks/differential-equations/
      - Numerical Methods: assignments/banks/numerical-methods/
      - Physics: assignments/banks/physics/
      - Engineering: assignments/banks/engineering/
      - CS: assignments/banks/cs/
      - Business: assignments/banks/business/
      - Law & Policy: assignments/banks/law/
  - Rubrics:
    - Problem Set: rubrics/problem-set-rubric.md
    - Lab Report: rubrics/lab-rubric.md
    - Engineering Project: rubrics/project-rubric-engineering.md
    - Case Study: rubrics/case-study-rubric.md
    - Presentation: rubrics/presentation-rubric.md
    - Essay: rubrics/essay-rubric.md
  - Advisors:
    - Pathways: advisors/pathways.md
  - Changelog: changelog.md
